// Copyright © Aptos Foundation
// SPDX-License-Identifier: Apache-2.0

//! # Tasmil Aptos Multi-Protocol DEX Indexer Library
//! 
//! Comprehensive indexing solution for tracking swap events and calculating 
//! trading volumes across multiple DEX protocols on Aptos.
//! 
//! ## Supported Protocols
//! - **Cellana**: Native AMM with concentrated liquidity
//! - **Thala**: Multi-asset stable and volatile pools
//! - **SushiSwap**: Cross-chain DEX with extensive trading pairs
//! - **LiquidSwap**: Native Aptos DEX with multiple pool types
//! - **Hyperion**: V3 protocol with range orders
//! 
//! ## Key Features
//! - Real-time transaction processing
//! - 24-hour rolling volume calculations
//! - Time-based bucketing for chart data (2-hour intervals)
//! - Protocol-specific fee tracking and aggregation
//! - High-performance PostgreSQL storage with connection pooling

/// Common utilities and shared components used across the indexer
pub mod common;

/// Configuration management for indexer processor and database settings
pub mod config;

/// Database layer including models, schema, and connection pooling
pub mod db;

/// Core processors for handling transactions and calculating volumes
pub mod processors;

/// Database schema definitions (auto-generated by Diesel)
/// This module contains the table definitions and relationships
/// used by the ORM for type-safe database operations
#[path = "db/postgres/schema.rs"]
pub mod schema;

/// Utility functions for database operations, chain validation, and data processing
pub mod utils;
